### Get a shortener url
GET https://you-apigateway.execute-api.us-east-1.amazonaws.com/{urlCode} HTTP/1.1
Content-Type: application/json

### Create a shortener url
POST https://you-apigateway.execute-api.us-east-1.amazonaws.com/create HTTP/1.1
Content-Type: application/json

{
  "originalUrl": "https://github.com/maycon8609/redirect-url-shortener",
  "expirationTime": "1735167600000"
}

# "expirationTime": "1735167600000" === 2024-12-25T20:00:00
